### ISSUE TITLE
get fake Input report, when immediately after doing setOutptReport

### ISSUE THREAD

**Issue by kahamberg** [nyholku/purejavahidapi#49]
I'm using w10x64. I have a device that receives and sends two-byte reports on port 0.
For example, I will send it a query code and it will return a response.

After I first send the first report, I receive the response just fine via onInputReport. Second and subsequent report sends, cause the previous in-report to arrive via onInputReport (even if the remote micro does not send an in-report). In addition, any in report the remote micro does send will also arrive. 
So after the first out-report (from the PC to the USB micro) I get one in report as I expect.
After the second out-report I will get the previous in report immediately (not expected or wanted), then will get the actual in-report I am expecting. If I put a breakpoint in the java on the in report, I catch the previous report, and will never get the in-report.

As an aside, this is a nice library and I like it. Thank you.

**Comment by nyholku** [comment]
Interesting. I don't use this much on Windows so my experience is limited. 
If you look at the code that does the input report listening:

https://github.com/nyholku/purejavahidapi/blob/55fcca51a2f827acf3c83b0a05c42242e6cb71fa/src/purejavahidapi/windows/HidDevice.java#L242

you'll see that it is very simple loop and difficult to see of hand how it can happen that you see what you are seeing.  Of course it is true that the same buffer is used over and over again so if the there logic here is faulty you would see the last report multiple times. 

You could investigate ,by modifying the above code to clear the buffer after each read or fill it with some special value,  to see if you are really receiving the data multiple times or if this loop is somehow tricked to report it multiple times.

I do not have time to investigate this right now.

**Comment by MrHazee** [comment]
Hi there! I have the exakt same problem. 
Did anyone of you ever found a soloution for this? 
I also get this exception:

Exception in thread "TxThread" java.lang.IndexOutOfBoundsException: Bounds exceeds available space : size=65, offset=74
at com.sun.jna.Memory.boundsCheck(Memory.java:186)
at com.sun.jna.Memory.write(Memory.java:308)
 
This occurs when I for example send, let us say 10 bytes(seven times) with setOutputReport(). Even if I sendone report every second.. so the time intervall between the setOutputReports() doesnt seem to matter.
It almoast feels like the senOutputReport-buffer doesnt clear it self after a transmission.
Im using the jars, should i compile with the source files instead?
Any ideas would be awesome!
Thanks a bunch!!
/Rasmus

**Comment by MrHazee** [comment]
Ps.Win 10/64, eclipse, but my intensions are to use the program on Mac as ds.

**Comment by MichaelBMiner** [comment]
I think I am having a similar issue and my fix was just to put a 25 millisecond wait before a read. The same file mentioned above I put in 
`m_InputReportBytesRead[0]--;
				try {
					Thread.sleep(25);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				m_InputReportMemory.read(1, m_InputReportBytes, 0, m_InputReportBytesRead[0]);`

**Comment by MrHazee** [comment]
Actually I tried that out as well, without any success... and my app is time critical so I cant afford 25 ms wait every usb-frame
